### PR TITLE
fix: Fix hung launcher on shutdown of Safari

### LINKED ISSUE #24: Safari doesn't always shut down properly
The Safari tests for [Shaka Player](https://github.com/google/shaka-player) in GitHub Actions seem to succeed, but the job doesn't shut down properly and eventually times out after ~6h. This seems likely to be a bug in the launcher.

### PR DESCRIPTION
**Pull request by joeyparrish**
In some cases (notably macOS Safari under GitHub Actions), a call to
forceKill() would be triggered during another call to forceKill().
This could cause the second Promise to go unresolved, leading to a
hang.  On GitHub, eventually, the workflow would be cancelled.

This fixes the nested calls to forceKill by making them both resolve
on the same event (the shutdown triggered by the first call).

This also adds a timeout for shutting down a WebDriver session.
Although this does not appear to be the root cause of the hang we
were experiencing in GitHub Actions workflows, it should be safer to
have this timeout.  If we can't stop a WebDriver session gracefully,
we will timeout after 5s and end the launcher anyway.

Closes #24

### CODE REVIEW

**Comment by joeyparrish** [comment]
I was led to this change by lots of console.log-based debugging and tracing through both Karma and the launcher.  With the logging still in place, I can see that the mitigations are active.

With this change, I've been able to run Shaka's tests on Safari, in the GitHub Actions environment, ~18~ 24 times in a row (and counting) without any hanging at the end.

File: index.js [hunk 1]
```diff
@@ -26,6 +26,9 @@ const {installWebDrivers} = require('webdriver-installer');
 const DRIVER_CACHE = path.join(os.homedir(), '.webdriver-installer-cache');
 fs.mkdirSync(DRIVER_CACHE, {recursive: true});
 
+// If it takes longer than this to close our WebDriver session, give up.
+const CLOSE_WEBDRIVER_SESSION_TIMEOUT_SECONDS = 5;
```
Comment (theodab) [inline index.js:33]: If you're adding this constant, why not add a constant to the 2s delay on start?

Comment (joeyparrish) [reply index.js:33]: Good call.  No reason not to.

File: index.js [hunk 2]
```diff
@@ -116,9 +119,18 @@ const LocalWebDriverBase = function(baseBrowserDecorator, args, logger) {
     await this.stopWebdriver_();
```
Comment (theodab) [inline index.js:122]: Say, what's the difference between the `kill` and `forceKill` operations? They both just call `stopWebdriver_`.
Is `kill` called in such a way that we don't need to worry about them being nested, or about a `forceKIll` being nested inside a `kill`?

Comment (joeyparrish) [reply index.js:122]: kill() and forceKill() are part of the launcher API, but in my logs, I don't see kill() being called.  In a purely external-process-based launcher, the base classes would send different POSIX signals to the subprocess for kill() and forceKill() if I recall correctly.

I initially thought forceKill() should never fail or be infinitely delayed, so I tried adding a timeout at the level of forceKill().  But that didn't solve the issue.  In the end, I added the timeout to the WebDriver quit command, since that's the only thing that can fail or be delayed.

So after all the debugging and logging, I concluded that kill() and forceKill() can still effectively be the same, except for the state tracking part.

Comment (theodab) [reply index.js:122]: I see. I was going to suggest moving the new logic for saving the operation as a promise into `stopWebdriver_`, instead of `forceKill`. But if `kill` isn't being called I guess it doesn't matter.

**Review by theodab — APPROVED** [review]
